apiVersion: apps/v1
kind: Deployment
metadata:
    name: firstproject
    namespace: default
    labels:
        app: firstproject
spec:
    replicas: 3
    selector:
        matchLabels:
            app: firstproject
    template:
        metadata:
            labels:
                app: firstproject
        spec:
            containers:
                - name: firstproject
                  image: sevinnn/flask-app
                  ports:
                      - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
    name: firstproject
    namespace: default
spec:
    selector:
        app: firstproject
    ports:
        - protocol: TCP
          port: 5000
          targetPort: 5000
    type: LoadBalancer